# Generated by Django 5.2.4 on 2025-09-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Management_APIs', '0001_initial'),
        ('Patient_Doctor_Mapping_APIs', '0001_initial'),
        ('Patient_Management_APIs', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='Doctor_Management_APIs.doctor'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='Patient_Management_APIs.patient'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
